# CONFIGURATION DU PORTFOLIO JEKYLL
# Informations du site

title: Mon Portfolio
author: Meegy
email: alison.dehaies@epitech.eu
description: >-
  Bienvenu sur mon Portfolio ! Vous y trouverez mes projets réalisés durant mon cursus à Epitech ainsi que quelques projets personnels.
  N'hésitez pas à me contacter via les réseaux sociaux ou par email !
  Bonne visite !
# Nom d'user réseaux
github_username: Meegy-exe
linkedin_username: alison-dehaies-dev
# Site URL settings
baseurl: "/Portfolio" # the subpath of your site, e.g. /blog
url: "https://meegy-exe.github.io"

# Avatar
avatar: "/assets/images/profil.jpg"

# THEME ACTUEL
theme: jekyll-theme-midnight


# jekyll prend en compte les collections pour les projets, analyse _projects, déclare en pages et genere les

collections:
  projects:
    output: true